from distutils.core import setup

setup(
    name='ideensammlung',
    version='',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip.vcs', 'venv.lib.python2.7.site-packages.pip.vendor',
              'venv.lib.python2.7.site-packages.pip.vendor.distlib',
              'venv.lib.python2.7.site-packages.pip.vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip.vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip.vendor.html5lib.trie',
              'venv.lib.python2.7.site-packages.pip.vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip.vendor.html5lib.serializer',
              'venv.lib.python2.7.site-packages.pip.vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip.vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip.commands', 'venv.lib.python2.7.site-packages.pip.backwardcompat',
              'venv.lib.python2.7.site-packages.flask', 'venv.lib.python2.7.site-packages.flask.ext',
              'venv.lib.python2.7.site-packages.flask.testsuite',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.lib.python2.5.site-packages.site_package',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.path.installed_package',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.flaskext',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.flaskext.oldext_package',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp.apps',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp.apps.admin',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.moduleapp.apps.frontend',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp.apps',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp.apps.admin',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.blueprintapp.apps.frontend',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.flask_broken',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.config_package_app',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.subdomaintestmodule',
              'venv.lib.python2.7.site-packages.flask.testsuite.test_apps.flask_newext_package',
              'venv.lib.python2.7.site-packages.google.protobuf',
              'venv.lib.python2.7.site-packages.google.protobuf.compiler',
              'venv.lib.python2.7.site-packages.google.protobuf.internal', 'venv.lib.python2.7.site-packages.jinja2',
              'venv.lib.python2.7.site-packages.jinja2.testsuite',
              'venv.lib.python2.7.site-packages.jinja2.testsuite.res', 'venv.lib.python2.7.site-packages.wtforms',
              'venv.lib.python2.7.site-packages.wtforms.ext', 'venv.lib.python2.7.site-packages.wtforms.ext.csrf',
              'venv.lib.python2.7.site-packages.wtforms.ext.i18n',
              'venv.lib.python2.7.site-packages.wtforms.ext.django',
              'venv.lib.python2.7.site-packages.wtforms.ext.django.templatetags',
              'venv.lib.python2.7.site-packages.wtforms.ext.dateutil',
              'venv.lib.python2.7.site-packages.wtforms.ext.appengine',
              'venv.lib.python2.7.site-packages.wtforms.ext.sqlalchemy',
              'venv.lib.python2.7.site-packages.wtforms.fields', 'venv.lib.python2.7.site-packages.wtforms.widgets',
              'venv.lib.python2.7.site-packages.werkzeug', 'venv.lib.python2.7.site-packages.werkzeug.debug',
              'venv.lib.python2.7.site-packages.werkzeug.contrib',
              'venv.lib.python2.7.site-packages.werkzeug.testsuite',
              'venv.lib.python2.7.site-packages.werkzeug.testsuite.contrib',
              'venv.lib.python2.7.site-packages.flask_wtf', 'venv.lib.python2.7.site-packages.flask_wtf.recaptcha',
              'venv.lib.python2.7.site-packages.rethinkdb', 'venv.lib.python2.7.site-packages._markerlib',
              'venv.lib.python2.7.site-packages.markupsafe', 'venv.lib.python2.7.site-packages.setuptools',
              'venv.lib.python2.7.site-packages.setuptools.tests',
              'venv.lib.python2.7.site-packages.setuptools.command',
              'venv.lib.python2.7.site-packages.setuptools._backport',
              'venv.lib.python2.7.site-packages.setuptools._backport.hashlib'],
    url='',
    license='',
    author='Sebastian Gumprich',
    author_email='sebastian.gumprich@38.de',
    description=''
)
